apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app-1
  namespace: default
spec:
  interval: 15m
  path: "./iac/manifest/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app-1