apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-1
  labels:
    app: example-app-1
  namespace: default
spec:
  selector:
    matchLabels:
      app: example-app-1
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app-1
    spec:
      containers:
      - name: example-app-1
        image: 314876856196.dkr.ecr.us-east-1.amazonaws.com/demo-flux-aws-women/example-app:0.0.1
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: example-app-1
