apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: default
  labels:
    app: example-app-1
spec:
  selector:
    app: example-app-1
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer